### ISSUE TITLE
[misc] support High-Resolution Canonical Avatars &&  image-to-avatars

### ISSUE THREAD

**Issue by xdobetter** [IDEA-Research/DreamWaltz#11]
Hello, great job on your work! I have a couple of questions regarding it:

1. Can the current codebase support [High-Resolution Canonical Avatars](https://idea-research.github.io/DreamWaltz/#canonical_2)? What is its computational overhead compared to 64x64 avatars?

2. Can the current task accommodate image-to-avatar conversion?

**Comment by Yukun-Huang** [comment]
Hi, thanks for your interests!
1. The current codebase cannot support high-resolution canonical avatar creation. We are still working on the high-res animation part, which it is almost complete and will be released. It takes about 1.5 hours to create a high-res canonical avatar on one RTX 3090 (It might be out of memory for some complex characters like "Elsa in Frozen". For this case, a GPU with larger memory like A100 is required).
2. The current pipeline does not support image-to-avatar creation, but could be possible by using an image-prompt diffusion model e.g. [imagedream](https://github.com/bytedance/ImageDream).

**Comment by xdobetter** [comment]
Thank you for your sincere reply and I look forward to your upcoming release work. :)
