### ISSUE TITLE
Where do I get the pretrained ControlNet?

### ISSUE THREAD

**Issue by lyk412** [IDEA-Research/DreamWaltz#3]
Thanks for your great work! I met a problem when I want to download the pretrained model. I can not find the below models on the Hugging Face. 

```
MODEL_CARDS = {
    'pose': "fusing/stable-diffusion-v1-5-controlnet-openpose",
    'depth': "fusing/stable-diffusion-v1-5-controlnet-depth",
    'canny': "fusing/stable-diffusion-v1-5-controlnet-canny",
    'seg': "fusing/stable-diffusion-v1-5-controlnet-seg",
    'normal': "fusing/stable-diffusion-v1-5-controlnet-normal",
}
```

**Comment by Yukun-Huang** [comment]
Thanks for your comment! The pre-trained models of ControlNet have been moved to: [https://huggingface.co/lllyasviel/sd-controlnet-openpose](https://huggingface.co/lllyasviel/sd-controlnet-openpose). You can download the weights there.

**Comment by xmu-xiaoma666** [comment]
> Thanks for your comment! The pre-trained models of ControlNet have been moved to: https://huggingface.co/lllyasviel/sd-controlnet-openpose. You can download the weights there.

Hello,  How many gpu hours are needed to train your model on a single NVIDIA 3090?

**Comment by lyk412** [comment]
> > Thanks for your comment! The pre-trained models of ControlNet have been moved to: https://huggingface.co/lllyasviel/sd-controlnet-openpose. You can download the weights there.
> 
> Hello, How many gpu hours are needed to train your model on a single NVIDIA 3090?

Hi, it takes about 7 hours to finish the whole process for one avatar generation.
