### ISSUE TITLE
how to get 512 resolution results and how to extract mesh Thanks

### ISSUE THREAD

**Issue by 1406428260** [IDEA-Research/DreamWaltz#5]
nice job! 
1.how to get 512 resolution results
2.how to extract mesh
Thanks

**Comment by Yukun-Huang** [comment]
1. We use the same two-stage training paradigm as [Latent-NeRF](https://github.com/eladrich/latent-nerf): first training with 64x64 Latent-NeRF, then 512x512 RGB fine-tuning.
2. You may refer to the [extract_mesh](https://github.com/ashawkey/stable-dreamfusion/blob/5550b91862a3af7842bb04875b7f1211e5095a63/nerf/renderer.py#L366) function in [stable-dreamfusion](https://github.com/ashawkey/stable-dreamfusion).
