### ISSUE TITLE
Program stuck

### ISSUE THREAD

**Issue by xmu-xiaoma666** [IDEA-Research/DreamWaltz#6]
<img width="454" alt="image" src="https://github.com/IDEA-Research/DreamWaltz/assets/33897496/864c8b20-df70-4519-8159-dfe3d84264e3">

<img width="1147" alt="image" src="https://github.com/IDEA-Research/DreamWaltz/assets/33897496/b833ac57-929f-40d3-b0f8-3d7d25fe5e95">

When I was running DreamWaltz, the program got stuck. After debugging, I found that the code was stuck in the red box. Do you know what the reason is?

**Comment by Yukun-Huang** [comment]
I think the reason is that the `raymarching` module was not compiled successfully. You may delete the cache of the `raymarching` module (usually in `~/.cache/torch_extensions`) and then recompile it manually.

**Comment by liwenssss** [comment]
hi, @xmu-xiaoma666 do you solve it?
