### ISSUE TITLE
SMPL Initialization

### ISSUE THREAD

**Issue by huanngzh** [IDEA-Research/DreamWaltz#7]
Why is the depth map used to initialize a NeRF of canonical SMPL? Use color map rendered from mesh will be efficient.

**Comment by Yukun-Huang** [comment]
Hi, using color map to initialize NeRF brings unnecessary color priors, e.g. white foreground. We tend to initialize NeRF's geometry without introducing appearance preferences.

**Comment by Yukun-Huang** [comment]
Thank you so much for the threestudio implementation of [DreamWaltz](https://github.com/huanngzh/threestudio-dreamwaltz)! We really appreciate it.

**Comment by huanngzh** [comment]
Well, got it. Btw, I'm honored to implement such a good avatar generation work as an extension of threestudio.

**Comment by huanngzh** [comment]
During the implementation process, it was discovered that when your code exported the mesh, depth, and pose maps of SMPL, the rendered mesh were inconsistent with the other two forms in the same camera input, as shown in the figure below.
![err_pose](https://github.com/IDEA-Research/DreamWaltz/assets/78398294/8d7c73fd-7022-4abc-bf92-fc0665aef7f1)
Could you please let me submit a pull request to resolve this issue?

**Comment by Yukun-Huang** [comment]
Sure! Thanks for the bug report and please feel free to submit a pull request.
