### ISSUE TITLE
Given a particular SMPL pose and a camera location, can I get the 2d projection of it like openpose figures ?

### ISSUE THREAD

**Issue by mayank64ce** [IDEA-Research/DreamWaltz#9]
@Yukun-Huang Also I am very new to this 3D domain so I am not sure of the terminologies and how these values are actually represented in code.

**Comment by Yukun-Huang** [comment]
Yes, you can get a 2d projection map of keypoints given SMPL pose and camera params. This part of function is defined in:
https://github.com/IDEA-Research/DreamWaltz/blob/4d1003e2aed42216c6701bebbf3e60ed2dbf81d8/core/prompt/smpl_prompt.py#L321
